# Generated by Django 4.0.6 on 2022-08-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('subtitle', models.CharField(max_length=240)),
                ('post_img', models.ImageField(blank=True, upload_to='blog_image/')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_body', models.CharField(max_length=140000)),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.user')),
                ('post_tags', models.ManyToManyField(to='Blogs.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
