# Generated by Django 4.0.6 on 2022-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_user_email_alter_user_password_and_more'),
        ('Blogs', '0007_alter_post_post_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='Accounts.user'),
        ),
    ]
