# Generated by Django 4.0.6 on 2022-08-18 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_alter_user_profile_user_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='Profile',
        ),
    ]
